# -*- coding: utf-8 -*-
"""remember_python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Zg5GAtqa-JiBzaqYrZoQxiDaodACdGhH
"""

# -*- coding: utf-8 -*-

ctx = "olá mundo" #String
ctx2 = 2+2 #int
ctx3 = 2**3.3 #float
ctx4 = True #boolean
ctx4 = False #boolean

print(ctx)
print(ctx2)
print(ctx3)
print(ctx4)

if ctx2 > ctx3:
  print("ctx2 é maior")
else: 
  print("ctx3 é maior")

if ctx4 == False:
  print("ctx4 é falso")

# while
x = 1 

while x <= 10:
  print(x)
  x += 1

list1 = [1,2,3,4,5,6,7,8,9,10]
list2 = ["olá", "mundo", "!"]
list3 = [0,"Olá","biscoito","bolacha",9.99,True]

#for i in list1:
  #print(i)

for i in range(10,20,2):
  print(i)